spring.application.name=backend
# ==========================================
# 1. Credenciales de la Base de Datos
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_musica
spring.datasource.username=tiago
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_musica
spring.datasource.username=tiago
spring.datasource.password=admin

# ==========================================
# 2. Comportamiento de Hibernate (ORM)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "update" instruye a Spring a crear o modificar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# 3. Depuración
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Límites multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# Cloudinary 
cloudinary.url=cloudinary://demo